"""Join, summarize, and plot the pulse-independent trajectory experiment.

Inputs are generated by ``pulse-independent-ci.py``.  This script uses only
the Python standard library and NumPy, writes a compact analysis JSON, and
creates publication SVGs without Matplotlib.
"""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path

import numpy as np


SIGMA_X = math.sqrt(1.0 / (2.0 * 7.743e-3))
COLORS = {
    "ink": "#172033",
    "muted": "#5e6a7d",
    "grid": "#d9dee8",
    "population": "#0f766e",
    "product": "#d97706",
    "centroid": "#2457a7",
    "exact": "#111827",
    "full": "#2563eb",
    "reprop": "#c026d3",
    "threshold": "#b91c1c",
    "paper": "#fbfcfe",
}


def load_json(path: Path):
    with path.open(encoding="utf-8") as handle:
        return json.load(handle)


def write_json(path: Path, value) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(path.suffix + ".tmp")
    with temporary.open("w", encoding="utf-8") as handle:
        json.dump(value, handle, indent=2)
        handle.write("\n")
    temporary.replace(path)


def exact_key(center: float, kick: float) -> str:
    return f"center={center:.6g};kick={kick:.6g}"


def error_statistics(approximate, exact, scale: float = 1.0) -> dict:
    residual = (np.asarray(approximate) - np.asarray(exact)) / scale
    return {
        "rmse": float(np.sqrt(np.mean(residual**2))),
        "max_abs": float(np.max(np.abs(residual))),
        "mean_signed": float(np.mean(residual)),
    }


def rank_values(values: np.ndarray) -> np.ndarray:
    order = np.argsort(values, kind="mergesort")
    ranks = np.empty(values.size, dtype=float)
    index = 0
    while index < values.size:
        end = index + 1
        while end < values.size and values[order[end]] == values[order[index]]:
            end += 1
        ranks[order[index:end]] = 0.5 * (index + end - 1) + 1.0
        index = end
    return ranks


def spearman_correlation(x, y) -> float:
    x_array = np.asarray(x, dtype=float)
    y_array = np.asarray(y, dtype=float)
    x_rank = rank_values(x_array)
    y_rank = rank_values(y_array)
    return float(np.corrcoef(x_rank, y_rank)[0, 1])


def exact_comparison(regime: dict, exact_run: dict) -> dict:
    time = np.asarray(regime["time_fs"])
    exact_time = np.asarray(exact_run["time_fs"])
    fields = {
        "upper_population": ("upper_population", 1.0, "probability"),
        "product_qx_lt_0": ("product_qx_lt_0", 1.0, "probability"),
        "centroid_x": ("centroid_x", SIGMA_X, "initial_sigma_x"),
    }
    output = {}
    for name, (exact_name, scale, unit) in fields.items():
        reference = np.interp(time, exact_time, np.asarray(exact_run[exact_name]))
        full = error_statistics(regime["full"][name], reference, scale)
        reprop = error_statistics(regime["reprop_axe"][name], reference, scale)
        output[name] = {
            "unit": unit,
            "full": full,
            "reprop_axe": reprop,
            "lower_rmse": "full" if full["rmse"] < reprop["rmse"] else "reprop_axe",
            "rmse_penalty_reprop_minus_full": reprop["rmse"] - full["rmse"],
        }
    return output


def compact_comparison(comparison: dict) -> dict:
    return {
        key: value for key, value in comparison.items()
        if not key.endswith("_series")
    }


def build_analysis(
    baseline: dict,
    convergence: dict,
    sweep: dict,
    exact: dict,
    exact_spot_checks: dict,
) -> dict:
    exact_runs = {
        exact_key(
            run["regime"]["center_fraction"],
            run["regime"]["momentum_kick_sigma"],
        ): run["exact"]
        for run in exact["runs"]
    }
    regimes = []
    for aggregate in sweep["aggregate"]["regimes"]:
        configuration = aggregate["configuration"]
        key = exact_key(
            configuration["center_fraction"],
            configuration["momentum_kick_toward_ci_sigma_px"],
        )
        joined = {
            "key": key,
            "stage": aggregate["stage"],
            "center_fraction": configuration["center_fraction"],
            "momentum_kick_sigma":
                configuration["momentum_kick_toward_ci_sigma_px"],
            "seeds": aggregate["seeds"],
            "replicate_count": aggregate["replicate_count"],
            "fp_vs_reprop": compact_comparison(
                aggregate["comparison_of_replicate_means"]
            ),
            "replicate_statistics": aggregate["replicate_statistics"],
            "exact_accuracy": exact_comparison(aggregate, exact_runs[key]),
            "diagnostics": aggregate["diagnostics"],
        }
        joined["fp_vs_reprop"]["max_coherence_amplitude_error"] = float(
            np.max(np.abs(
                np.asarray(aggregate["full"]["coherence_amplitude"])
                - np.asarray(aggregate["reprop_axe"]["coherence_amplitude"])
            ))
        )
        joined["normalized_declared_errors"] = {
            "upper_population":
                joined["fp_vs_reprop"]["max_upper_population_error"] / 0.05,
            "product_probability":
                joined["fp_vs_reprop"]["max_product_probability_error"] / 0.05,
            "centroid_x":
                joined["fp_vs_reprop"]["max_centroid_x_error_sigma"] / 0.1,
        }
        regimes.append(joined)

    original = [item for item in regimes if item["stage"] == "original_center_sweep"]
    nuclear_threshold_failures = [
        item["key"] for item in original
        if item["fp_vs_reprop"]["max_centroid_x_error_sigma"] > 0.1
    ]
    population_rp_wins = sum(
        item["exact_accuracy"]["upper_population"]["lower_rmse"] == "reprop_axe"
        for item in regimes
    )
    product_full_wins = sum(
        item["exact_accuracy"]["product_qx_lt_0"]["lower_rmse"] == "full"
        for item in regimes
    )
    centroid_full_wins = sum(
        item["exact_accuracy"]["centroid_x"]["lower_rmse"] == "full"
        for item in regimes
    )
    replicate_exact_accuracy = []
    for run in sweep["runs"]:
        configuration = run["configuration"]
        key = exact_key(
            configuration["center_fraction"],
            configuration["momentum_kick_toward_ci_sigma_px"],
        )
        replicate_exact_accuracy.append(exact_comparison(run, exact_runs[key]))
    stage_analysis = json.loads(json.dumps(sweep["aggregate"]["stage_analysis"]))
    for stage in ("original_center_sweep", "adaptive_directional_kick"):
        selected = (
            original if stage == "original_center_sweep"
            else [item for item in regimes if item["center_fraction"] == 0.5]
        )
        stage_analysis[stage][
            "spearman_early_hops_vs_max_coherence_amplitude_error"
        ] = spearman_correlation(
            [item["fp_vs_reprop"]["early_hop_fraction"] for item in selected],
            [
                item["fp_vs_reprop"]["max_coherence_amplitude_error"]
                for item in selected
            ],
        )
    original_correlations = stage_analysis["original_center_sweep"][
        "spearman_early_hops_vs_errors"
    ]
    reached_half = any(
        item["fp_vs_reprop"]["early_hop_fraction"] >= 0.5 for item in regimes
    )

    finest_bma = baseline["bma_runs"][-1]
    return {
        "published_model_gate": {
            "passed": baseline["gate"]["passed"],
            "bma_figure6_rmse":
                finest_bma["figure6_comparison"]["rmse"],
            "bma_figure6_max_abs":
                finest_bma["figure6_comparison"]["max_abs"],
            "bma_finest_pair": baseline["bma_convergence_vs_finest"][-1],
            "oned_finest_pair": baseline["oned_convergence_vs_finest"][-1],
        },
        "trajectory_numerical_gate": convergence["comparison"],
        "sweep": {
            "replicates": sweep["completed_replicates"],
            "geometry_count_per_replicate": 4000,
            "seeds": [1701, 1702, 1703, 1704],
            "stage_analysis": stage_analysis,
            "regimes": regimes,
        },
        "exact_reference_summary": {
            "regime_count": len(regimes),
            "reprop_lower_population_rmse_count": population_rp_wins,
            "full_lower_product_rmse_count": product_full_wins,
            "full_lower_centroid_rmse_count": centroid_full_wins,
            "replicate_count": len(replicate_exact_accuracy),
            "replicate_reprop_lower_population_rmse_count": sum(
                item["upper_population"]["lower_rmse"] == "reprop_axe"
                for item in replicate_exact_accuracy
            ),
            "replicate_full_lower_product_rmse_count": sum(
                item["product_qx_lt_0"]["lower_rmse"] == "full"
                for item in replicate_exact_accuracy
            ),
            "replicate_full_lower_centroid_rmse_count": sum(
                item["centroid_x"]["lower_rmse"] == "full"
                for item in replicate_exact_accuracy
            ),
        },
        "exact_reference_spot_checks": exact_spot_checks,
        "verdict": {
            "hypothesis_within_reached_range": (
                "supported" if all(value > 0.0 for value in original_correlations.values())
                else "falsified"
            ),
            "original_spearman_correlations": original_correlations,
            "maximum_early_hop_fraction": max(
                item["fp_vs_reprop"]["early_hop_fraction"] for item in regimes
            ),
            "predeclared_half_early_hop_regime_reached": reached_half,
            "half_early_hop_falsifier_status": (
                "adjudicated" if reached_half else "inconclusive: regime not reached"
            ),
            "original_centroid_threshold_failures": nuclear_threshold_failures,
            "interpretation": (
                "The predicted association is supported over the observed "
                "0.073--0.261 early-hop range, but the planned >=0.5 validity "
                "boundary was not reached. Nuclear centroid error crosses its "
                "declared threshold before either electronic population or "
                "product probability; exact dynamics favors full propagation "
                "for both nuclear observables in every regime."
            ),
        },
    }


def svg_document(width: int, height: int, content: str, title: str) -> str:
    return f'''<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}" role="img" aria-labelledby="title desc">
<title id="title">{title}</title>
<desc id="desc">{title}</desc>
<rect width="100%" height="100%" fill="{COLORS['paper']}"/>
<style>
  text {{ font-family: Inter, ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; fill: {COLORS['ink']}; }}
  .tick {{ font-size: 17px; fill: {COLORS['muted']}; }}
  .axis-label {{ font-size: 21px; font-weight: 600; }}
  .title {{ font-size: 29px; font-weight: 700; }}
  .subtitle {{ font-size: 17px; fill: {COLORS['muted']}; }}
  .legend {{ font-size: 17px; }}
</style>
{content}
</svg>
'''


def polyline(points, color, width=4, dash=None, opacity=1.0) -> str:
    pairs = " ".join(f"{x:.2f},{y:.2f}" for x, y in points)
    dashed = f' stroke-dasharray="{dash}"' if dash else ""
    return (
        f'<polyline points="{pairs}" fill="none" stroke="{color}" '
        f'stroke-width="{width}" stroke-linecap="round" '
        f'stroke-linejoin="round" opacity="{opacity}"{dashed}/>'
    )


def marker(x, y, color, adaptive=False) -> str:
    if adaptive:
        size = 7
        return (
            f'<path d="M {x:.2f} {y-size:.2f} L {x+size:.2f} {y:.2f} '
            f'L {x:.2f} {y+size:.2f} L {x-size:.2f} {y:.2f} Z" '
            f'fill="{COLORS["paper"]}" stroke="{color}" stroke-width="3"/>'
        )
    return f'<circle cx="{x:.2f}" cy="{y:.2f}" r="6" fill="{color}" stroke="white" stroke-width="2"/>'


def figure_regime_map(analysis: dict, path: Path) -> None:
    width, height = 1200, 700
    left, right, top, bottom = 105, 1165, 145, 605
    x_min, x_max = 0.05, 0.28
    y_min, y_max = 0.0, 2.0

    def xmap(value):
        return left + (value - x_min) / (x_max - x_min) * (right - left)

    def ymap(value):
        return bottom - (value - y_min) / (y_max - y_min) * (bottom - top)

    pieces = [
        '<text x="105" y="48" class="title">FP versus RP-AXE error by early-hop fraction</text>',
        '<text x="105" y="78" class="subtitle">FP versus RP-AXE maximum errors, normalized by their predeclared tolerances</text>',
    ]
    for value in np.arange(0.0, 2.01, 0.5):
        y = ymap(value)
        pieces.append(
            f'<line x1="{left}" y1="{y:.2f}" x2="{right}" y2="{y:.2f}" '
            f'stroke="{COLORS["grid"]}" stroke-width="1"/>'
        )
        pieces.append(
            f'<text x="{left-17}" y="{y+6:.2f}" text-anchor="end" class="tick">{value:g}</text>'
        )
    for percent in (5, 10, 15, 20, 25):
        x = xmap(percent / 100.0)
        pieces.append(
            f'<line x1="{x:.2f}" y1="{top}" x2="{x:.2f}" y2="{bottom}" '
            f'stroke="{COLORS["grid"]}" stroke-width="1"/>'
        )
        pieces.append(
            f'<text x="{x:.2f}" y="{bottom+30}" text-anchor="middle" class="tick">{percent}</text>'
        )
    pieces.extend([
        f'<line x1="{left}" y1="{bottom}" x2="{right}" y2="{bottom}" stroke="{COLORS["ink"]}" stroke-width="2"/>',
        f'<line x1="{left}" y1="{top}" x2="{left}" y2="{bottom}" stroke="{COLORS["ink"]}" stroke-width="2"/>',
        f'<line x1="{left}" y1="{ymap(1):.2f}" x2="{right}" y2="{ymap(1):.2f}" stroke="{COLORS["threshold"]}" stroke-width="3" stroke-dasharray="9 7"/>',
        f'<text x="{right-8}" y="{ymap(1)-10:.2f}" text-anchor="end" fill="{COLORS["threshold"]}" font-size="17">declared limit</text>',
        f'<text x="{(left+right)/2:.2f}" y="{height-30}" text-anchor="middle" class="axis-label">Successful hops before C(0)/e (%)</text>',
        f'<text x="29" y="{(top+bottom)/2:.2f}" text-anchor="middle" class="axis-label" transform="rotate(-90 29 {(top+bottom)/2:.2f})">Maximum error / declared tolerance</text>',
    ])

    regimes = analysis["sweep"]["regimes"]
    original = [item for item in regimes if item["stage"] == "original_center_sweep"]
    adaptive = [
        item for item in regimes
        if item["center_fraction"] == 0.5
    ]
    adaptive.sort(key=lambda item: item["momentum_kick_sigma"])
    metrics = [
        ("upper_population", "population"),
        ("product_probability", "product"),
        ("centroid_x", "centroid"),
    ]
    for metric, color_name in metrics:
        color = COLORS[color_name]
        original_points = [(
            xmap(item["fp_vs_reprop"]["early_hop_fraction"]),
            ymap(item["normalized_declared_errors"][metric]),
        ) for item in original]
        adaptive_points = [(
            xmap(item["fp_vs_reprop"]["early_hop_fraction"]),
            ymap(item["normalized_declared_errors"][metric]),
        ) for item in adaptive]
        pieces.append(polyline(original_points, color, width=4))
        pieces.append(polyline(adaptive_points, color, width=3, dash="8 7", opacity=0.82))
        pieces.extend(marker(x, y, color, adaptive=False) for x, y in original_points)
        pieces.extend(marker(x, y, color, adaptive=True) for x, y in adaptive_points)

    legend_y = 108
    legend_items = [
        ("population", "upper-state population"),
        ("product", "P(qx &lt; 0)"),
        ("centroid", "qx centroid"),
    ]
    legend_x = 600
    for index, (color_name, label) in enumerate(legend_items):
        x = legend_x + index * 210
        pieces.append(f'<line x1="{x}" y1="{legend_y}" x2="{x+30}" y2="{legend_y}" stroke="{COLORS[color_name]}" stroke-width="4"/>')
        pieces.append(f'<text x="{x+38}" y="{legend_y+6}" class="legend">{label}</text>')
    pieces.append(f'<circle cx="106" cy="{legend_y}" r="6" fill="{COLORS["ink"]}"/><text x="121" y="{legend_y+6}" class="tick">original center sweep</text>')
    pieces.append(f'<path d="M 325 {legend_y-7} L 332 {legend_y} L 325 {legend_y+7} L 318 {legend_y} Z" fill="white" stroke="{COLORS["ink"]}" stroke-width="3"/><text x="344" y="{legend_y+6}" class="tick">adaptive directional kick</text>')
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(svg_document(width, height, "\n".join(pieces), "FP versus RP-AXE error by early-hop fraction"), encoding="utf-8")


def axis_panel(pieces, x0, x1, y0, y1, ymin, ymax, yticks, title, ylabel):
    for value in yticks:
        y = y1 - (value - ymin) / (ymax - ymin) * (y1 - y0)
        pieces.append(f'<line x1="{x0}" y1="{y:.2f}" x2="{x1}" y2="{y:.2f}" stroke="{COLORS["grid"]}"/>')
        pieces.append(f'<text x="{x0-13}" y="{y+6:.2f}" text-anchor="end" class="tick">{value:g}</text>')
    for value in (0, 5, 10, 15, 20):
        x = x0 + value / 20.0 * (x1 - x0)
        pieces.append(f'<line x1="{x:.2f}" y1="{y0}" x2="{x:.2f}" y2="{y1}" stroke="{COLORS["grid"]}"/>')
        pieces.append(f'<text x="{x:.2f}" y="{y1+29}" text-anchor="middle" class="tick">{value}</text>')
    pieces.append(f'<line x1="{x0}" y1="{y1}" x2="{x1}" y2="{y1}" stroke="{COLORS["ink"]}" stroke-width="2"/>')
    pieces.append(f'<line x1="{x0}" y1="{y0}" x2="{x0}" y2="{y1}" stroke="{COLORS["ink"]}" stroke-width="2"/>')
    pieces.append(f'<text x="{x0}" y="{y0-18}" font-size="22" font-weight="700">{title}</text>')
    pieces.append(f'<text x="{(x0+x1)/2:.2f}" y="{y1+63}" text-anchor="middle" class="axis-label">time (fs)</text>')
    pieces.append(f'<text x="{x0-65}" y="{(y0+y1)/2:.2f}" text-anchor="middle" class="axis-label" transform="rotate(-90 {x0-65} {(y0+y1)/2:.2f})">{ylabel}</text>')


def figure_exact_contrast(sweep: dict, exact: dict, analysis: dict, path: Path) -> None:
    aggregate = next(
        item for item in sweep["aggregate"]["regimes"]
        if item["configuration"]["center_fraction"] == 0.5
        and item["configuration"]["momentum_kick_toward_ci_sigma_px"] == 0.0
    )
    exact_run = next(
        item["exact"] for item in exact["runs"]
        if item["regime"]["center_fraction"] == 0.5
        and item["regime"]["momentum_kick_sigma"] == 0.0
    )
    joined = next(item for item in analysis["sweep"]["regimes"] if item["key"] == "center=0.5;kick=0")
    time = np.asarray(aggregate["time_fs"])
    exact_time = np.asarray(exact_run["time_fs"])

    width, height = 1200, 700
    pieces = [
        '<text x="75" y="47" class="title">Trajectory means versus exact quantum dynamics</text>',
        '<text x="75" y="77" class="subtitle">Original center sweep at qx,0/(a/2) = 0.5; four-seed trajectory means versus exact quantum dynamics</text>',
    ]
    panels = [
        (80, 555, 160, 570, 0.0, 0.32, [0, 0.1, 0.2, 0.3], "A  Electronic population", "upper population", "upper_population"),
        (705, 1175, 160, 570, 7.0, 11.2, [7, 8, 9, 10, 11], "B  Nuclear centroid", "qx (mass-weighted a.u.)", "centroid_x"),
    ]
    for x0, x1, y0, y1, ymin, ymax, ticks, title, ylabel, field in panels:
        axis_panel(pieces, x0, x1, y0, y1, ymin, ymax, ticks, title, ylabel)

        def map_points(values, times=time):
            return [(
                x0 + t / 20.0 * (x1 - x0),
                y1 - (v - ymin) / (ymax - ymin) * (y1 - y0),
            ) for t, v in zip(times, values)]

        exact_values = np.interp(time, exact_time, np.asarray(exact_run[field]))
        pieces.append(polyline(map_points(exact_values), COLORS["exact"], width=5))
        pieces.append(polyline(map_points(aggregate["full"][field]), COLORS["full"], width=4))
        pieces.append(polyline(map_points(aggregate["reprop_axe"][field]), COLORS["reprop"], width=4, dash="9 6"))

        accuracy = joined["exact_accuracy"][field]
        annotation_y = y0 + 30
        annotation_x = x0 + (225 if field == "upper_population" else 18)
        unit = "" if field == "upper_population" else " σx"
        pieces.append(
            f'<text x="{annotation_x}" y="{annotation_y}" font-size="16" fill="{COLORS["muted"]}">RMSE: FP {accuracy["full"]["rmse"]:.3f}{unit}; RP {accuracy["reprop_axe"]["rmse"]:.3f}{unit}</text>'
        )

    legend_x, legend_y = 410, 110
    for index, (color, label, dash) in enumerate([
        (COLORS["exact"], "exact quantum", None),
        (COLORS["full"], "full propagation", None),
        (COLORS["reprop"], "RP-AXE", "9 6"),
    ]):
        x = legend_x + index * 210
        dash_attr = f' stroke-dasharray="{dash}"' if dash else ""
        pieces.append(f'<line x1="{x}" y1="{legend_y}" x2="{x+34}" y2="{legend_y}" stroke="{color}" stroke-width="4"{dash_attr}/><text x="{x+43}" y="{legend_y+6}" class="legend">{label}</text>')
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(svg_document(width, height, "\n".join(pieces), "Trajectory means versus exact quantum dynamics"), encoding="utf-8")


def figure_baseline(baseline: dict, path: Path) -> None:
    finest = baseline["bma_runs"][-1]
    time = np.asarray(finest["time_fs"])
    simulation = np.asarray(finest["upper_population"])
    reference_time = np.asarray(finest["figure6_comparison"]["time_fs"])
    reference = np.asarray(finest["figure6_comparison"]["digitized"])
    width, height = 1000, 590
    left, right, top, bottom = 95, 960, 105, 500

    def xmap(value): return left + value / 40.0 * (right - left)
    def ymap(value): return bottom - value / 0.24 * (bottom - top)

    pieces = [
        '<text x="95" y="43" class="title">Published BMA population benchmark</text>',
        '<text x="95" y="72" class="subtitle">Digitized exact curve from Mannouch and Kelly Figure 6 versus this split-operator solver</text>',
    ]
    for value in (0.0, 0.05, 0.10, 0.15, 0.20):
        y = ymap(value)
        pieces.append(f'<line x1="{left}" y1="{y:.2f}" x2="{right}" y2="{y:.2f}" stroke="{COLORS["grid"]}"/>')
        pieces.append(f'<text x="{left-14}" y="{y+6:.2f}" text-anchor="end" class="tick">{value:.2f}</text>')
    for value in (0, 10, 20, 30, 40):
        x = xmap(value)
        pieces.append(f'<line x1="{x:.2f}" y1="{top}" x2="{x:.2f}" y2="{bottom}" stroke="{COLORS["grid"]}"/>')
        pieces.append(f'<text x="{x:.2f}" y="{bottom+29}" text-anchor="middle" class="tick">{value}</text>')
    pieces.append(polyline([(xmap(t), ymap(v)) for t, v in zip(time, simulation)], COLORS["full"], width=5))
    pieces.append(polyline([(xmap(t), ymap(v)) for t, v in zip(reference_time, reference)], COLORS["exact"], width=4, dash="9 7"))
    pieces.extend([
        f'<line x1="{left}" y1="{bottom}" x2="{right}" y2="{bottom}" stroke="{COLORS["ink"]}" stroke-width="2"/>',
        f'<line x1="{left}" y1="{top}" x2="{left}" y2="{bottom}" stroke="{COLORS["ink"]}" stroke-width="2"/>',
        f'<text x="{(left+right)/2}" y="{height-25}" text-anchor="middle" class="axis-label">time (fs)</text>',
        f'<text x="27" y="{(top+bottom)/2}" text-anchor="middle" class="axis-label" transform="rotate(-90 27 {(top+bottom)/2})">upper population</text>',
        f'<text x="655" y="128" font-size="17">RMSE {finest["figure6_comparison"]["rmse"]:.4f}; max |error| {finest["figure6_comparison"]["max_abs"]:.4f}</text>',
        f'<line x1="655" y1="154" x2="690" y2="154" stroke="{COLORS["full"]}" stroke-width="5"/><text x="700" y="160" class="legend">split operator</text>',
        f'<line x1="815" y1="154" x2="850" y2="154" stroke="{COLORS["exact"]}" stroke-width="4" stroke-dasharray="9 7"/><text x="860" y="160" class="legend">paper</text>',
    ])
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(svg_document(width, height, "\n".join(pieces), "Published BMA population benchmark"), encoding="utf-8")


def parse_args():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--baseline", type=Path, default=Path("downloads/pulse_ci_baseline.json"))
    parser.add_argument("--convergence", type=Path, default=Path("downloads/pulse_ci_convergence.json"))
    parser.add_argument("--sweep", type=Path, default=Path("downloads/pulse_ci_sweep.json"))
    parser.add_argument("--exact", type=Path, default=Path("downloads/pulse_ci_exact_regimes.json"))
    parser.add_argument(
        "--exact-spot-checks",
        type=Path,
        default=Path("downloads/pulse_ci_exact_spot_checks.json"),
    )
    parser.add_argument("--output", type=Path, default=Path("downloads/pulse_ci_analysis.json"))
    parser.add_argument("--image-dir", type=Path, default=Path("images"))
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    baseline = load_json(args.baseline)
    convergence = load_json(args.convergence)
    sweep = load_json(args.sweep)
    exact = load_json(args.exact)
    exact_spot_checks = load_json(args.exact_spot_checks)
    analysis = build_analysis(
        baseline,
        convergence,
        sweep,
        exact,
        exact_spot_checks,
    )
    write_json(args.output, analysis)
    figure_regime_map(
        analysis,
        args.image_dir / "2026-07-18-pulse-independent-regime-map.svg",
    )
    figure_exact_contrast(
        sweep,
        exact,
        analysis,
        args.image_dir / "2026-07-18-pulse-independent-exact-contrast.svg",
    )
    figure_baseline(
        baseline,
        args.image_dir / "2026-07-18-pulse-independent-baseline.svg",
    )
    print(json.dumps(analysis["verdict"], indent=2))
    print(json.dumps(analysis["exact_reference_summary"], indent=2))
    print(f"wrote {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
