#!/usr/bin/env node

// Renders results/frontier_orbitals.json as an inline-SVG energy-level figure
// for the acceptor-strength post, one panel per functional. Deterministic:
// same input, same bytes.

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const experimentDir = dirname(fileURLToPath(import.meta.url));
const root = resolve(experimentDir, '../..');
const inputPath = resolve(experimentDir, 'results/frontier_orbitals.json');
const outputPath = resolve(experimentDir, 'results/figure_frontier_levels.html');
const checkOnly = process.argv.includes('--check');

const ACCEPTORS = ['CN', 'DCV', 'TCF'];        // weak -> strong acceptor
const PANELS = [
  { fn: 'cam-b3lyp', title: 'CAM-B3LYP / def2-TZVP' },
  { fn: 'b3lyp', title: 'B3LYP / def2-TZVP' },
];

// Shared scale across both panels, eV.
const Y_TOP = 0.6, Y_BOT = -10.2, PX_PER_EV = 38;
const M_L = 42, M_T = 8, M_B = 38, M_R = 6, COL = 72;
const PLOT_H = (Y_TOP - Y_BOT) * PX_PER_EV;
const W = M_L + ACCEPTORS.length * COL + M_R;
const H = M_T + PLOT_H + M_B;
const y = (ev) => (M_T + (Y_TOP - ev) * PX_PER_EV).toFixed(1);
const colX = (i) => M_L + COL * (i + 0.5);

const records = JSON.parse(readFileSync(inputPath, 'utf8')).molecules;
const rec = (acc, fn) => {
  const r = records.find((m) => m.acceptor === acc && m.functional === fn);
  if (!r) throw new Error(`no record for ${acc}/${fn} in ${inputPath}`);
  return r;
};

function level(x, ev, half, cls, title) {
  return `<line class="${cls}" x1="${(x - half).toFixed(1)}" y1="${y(ev)}" `
    + `x2="${(x + half).toFixed(1)}" y2="${y(ev)}"><title>${title}: `
    + `${ev.toFixed(2)} eV</title></line>`;
}

function panel({ fn, title }) {
  const parts = [];
  for (let g = 0; g >= -10; g--) {
    parts.push(`<line class="fl-grid" x1="${M_L}" y1="${y(g)}" x2="${W - M_R}" y2="${y(g)}"/>`);
    if (g % 2 === 0) {
      parts.push(`<text class="fl-axis" x="${M_L - 6}" y="${(+y(g) + 3.5).toFixed(1)}" `
        + `text-anchor="end">${g === 0 ? '0' : '−' + Math.abs(g)}</text>`);
    }
  }
  parts.push(`<text class="fl-axis" x="${M_L - 6}" y="${(+y(Y_TOP) + 4).toFixed(1)}" text-anchor="end">eV</text>`);

  ACCEPTORS.forEach((acc, i) => {
    const x = colX(i);
    const r = rec(acc, fn);
    const gapTop = +y(r.lumo_eV) + 7, gapBot = +y(r.homo_eV) - 7;
    parts.push(`<line class="fl-gapline" x1="${x}" y1="${gapTop.toFixed(1)}" x2="${x}" y2="${gapBot.toFixed(1)}"/>`);
    parts.push(`<text class="fl-gaplabel" x="${x}" y="${(((+y(r.lumo_eV)) + (+y(r.homo_eV))) / 2 + 3.5).toFixed(1)}" `
      + `text-anchor="middle">${r.gap_eV.toFixed(2)}</text>`);
    parts.push(level(x, r.homo_minus_1_eV, 14, 'fl-flank', `${acc}: HOMO−1`));
    parts.push(level(x, r.lumo_plus_1_eV, 14, 'fl-flank', `${acc}: LUMO+1`));
    parts.push(level(x, r.homo_eV, 21, 'fl-homo', `${acc}: HOMO`));
    parts.push(level(x, r.lumo_eV, 21, 'fl-lumo', `${acc}: LUMO`));
    parts.push(`<text class="fl-col" x="${x}" y="${H - 20}" text-anchor="middle">${acc}</text>`);
  });
  parts.push(`<text class="fl-axis" x="${M_L + ACCEPTORS.length * COL / 2}" y="${H - 4}" `
    + `text-anchor="middle">acceptor, weak → strong</text>`);

  return `<div class="fl-panel">
<p class="fl-title">${title}</p>
<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="Frontier-orbital energy levels of the three acceptors under ${title}; exact values in Table 1">
${parts.join('\n')}
</svg>
</div>`;
}

const snippet = `<!-- Generated by research/meo-acceptor-ladder/make-figure.mjs from
     results/frontier_orbitals.json. Do not hand-edit; regenerate and re-paste. -->
<div class="fig-levels">
<style>
.fig-levels { --fl-homo: var(--accent, #465C9B); --fl-lumo: var(--terracotta, #B76842); }
[data-theme='dark'] .fig-levels { --fl-homo: #6B89D9; --fl-lumo: #C9713F; }
.fig-levels .fl-panels { display: flex; flex-wrap: wrap; gap: 1rem; }
.fig-levels .fl-panel { flex: 1 1 17rem; min-width: 0; background: var(--offwhite);
  border: 1px solid var(--border); border-radius: 8px; padding: 0.8rem 0.8rem 0.4rem; }
.fig-levels .fl-panel svg { width: 100%; height: auto; display: block; }
.fig-levels .fl-title { margin: 0 0 0.2rem; font-size: 0.85rem; font-weight: 600; color: var(--text); }
.fig-levels svg text { font-family: 'Hanken Grotesk', system-ui, sans-serif;
  font-variant-numeric: tabular-nums; fill: var(--faint); font-size: 10.5px; }
.fig-levels .fl-sub { font-size: 8px; }
.fig-levels .fl-col { fill: var(--text); font-size: 12px; }
.fig-levels .fl-grid { stroke: var(--border); stroke-width: 1; }
.fig-levels .fl-homo { stroke: var(--fl-homo); stroke-width: 3; stroke-linecap: round; }
.fig-levels .fl-lumo { stroke: var(--fl-lumo); stroke-width: 3; stroke-linecap: round; }
.fig-levels .fl-flank { stroke: var(--muted); stroke-width: 1.4; stroke-dasharray: 4 3; }
.fig-levels .fl-gapline { stroke: var(--border-strong); stroke-width: 1; }
.fig-levels .fl-gaplabel { fill: var(--slate); paint-order: stroke; stroke: var(--offwhite); stroke-width: 4; }
.fig-levels .fl-legend { display: flex; flex-wrap: wrap; gap: 0.4rem 1.4rem; align-items: center;
  margin-top: 0.6rem; font-size: 0.8rem; color: var(--muted); }
.fig-levels .fl-key { display: inline-flex; align-items: center; gap: 0.45rem; }
.fig-levels .fl-swatch { display: inline-block; width: 22px; height: 3px; border-radius: 2px; }
.fig-levels .fl-swatch-dash { display: inline-block; width: 22px; height: 0;
  border-top: 2px dashed var(--muted); }
</style>
<div class="fl-panels">
${PANELS.map(panel).join('\n')}
</div>
<div class="fl-legend"><span class="fl-key"><span class="fl-swatch" style="background: var(--fl-homo)"></span>HOMO</span> <span class="fl-key"><span class="fl-swatch" style="background: var(--fl-lumo)"></span>LUMO</span> <span class="fl-key"><span class="fl-swatch-dash"></span>HOMO−1 · LUMO+1</span> <span class="fl-key">connector value: ε(LUMO) − ε(HOMO), eV</span></div>
</div>
`;

if (checkOnly) {
  if (!existsSync(outputPath) || readFileSync(outputPath, 'utf8') !== snippet) {
    console.error(`${relative(root, outputPath)} is missing or stale`);
    process.exit(1);
  }
} else {
  writeFileSync(outputPath, snippet);
  console.log(`wrote ${relative(root, outputPath)}`);
}
